export GRAFANA_URL="https://grafana.taller.ai"
export GRAFANA_API_KEY={{ op://Developer Secrets/Grafana/credential }}
export MP_CLIENT_ID={{ op://Developer Secrets/MercadoPago/client_id }}
export MP_CLIENT_SECRET={{ op://Developer Secrets/MercadoPago/client_secret }}
export MERCADO_PAGO_MCP_ACCESS_TOKEN={{ op://Developer Secrets/MercadoPago/mcp_access_token }}
export CLOUDFLARE_API_TOKEN={{ op://Developer Secrets/Cloudflare/credential }}
export ANTHROPIC_API_KEY={{ op://Developer Secrets/Anthropic/credential }}
export ENGBIM_BITBUCKET_TOKEN={{ op://Developer Secrets/Bitbucket ENGBIM API Token/credential }}
export ENGBIM_BITBUCKET_USERNAME={{ op://Developer Secrets/Bitbucket ENGBIM API Token/username }}
export ENGBIM_BITBUCKET_WORKSPACE={{ op://Developer Secrets/Bitbucket ENGBIM API Token/workspace }}
# Orca Bitbucket integration (PRs + build statuses). Read by Orca.app via env.
export ORCA_BITBUCKET_EMAIL={{ op://Developer Secrets/Bitbucket ENGBIM API Token/username }}
export ORCA_BITBUCKET_API_TOKEN={{ op://Developer Secrets/Bitbucket ENGBIM API Token/credential }}
export ZAI_API_KEY={{ op://Developer Secrets/ZAI Coding/credential }}
export OPENROUTER_API_KEY={{ op://Developer Secrets/OpenRouter/credential }}
export GODADDY_API_KEY={{ op://Developer Secrets/GoDaddy/credential }}
export GODADDY_API_SECRET={{ op://Developer Secrets/GoDaddy/secret }}
export GODADDY_GOPLY_API_KEY={{ op://Developer Secrets/GoDaddyGoply/credential }}
export GODADDY_GOPLY_API_SECRET={{ op://Developer Secrets/GoDaddyGoply/secret }}
